stef_dag_van_de_week_homepage:
    path:     /
    defaults: { _controller: StefDagVanDeWeekBundle:Index:index }

stef_dag_van_de_week_sitemaps:
    pattern:  /sitemaps/{mappingKey}.xml
    defaults: { _controller: StefDagVanDeWeekBundle:Sitemap:generate }
    requirements:
        _method:  GET
        _format:  xml

stef_dag_van_de_week_calendar_routing:
    resource: "@StefDagVanDeWeekBundle/Resources/config/calendar_routing.yml"

stef_dag_van_de_week_history_routing:
    resource: "@StefDagVanDeWeekBundle/Resources/config/history_routing.yml"

stef_dag_van_de_week_weekhero_routing:
    resource: "@StefDagVanDeWeekBundle/Resources/config/weekhero_routing.yml"

stef_dag_van_de_week_special_days_by_year:
    pattern:  /bijzondere-dagen-{year}
    defaults: { _controller: StefDagVanDeWeekBundle:SpecialDates:show }
    requirements:
        _method:  GET
        year:  \d+

stef_dag_van_de_week_news_archive_index:
    pattern:  /nieuws
    defaults: { _controller: StefDagVanDeWeekBundle:News:showMainNewsPage }
    requirements:
        _method:  GET

stef_dag_van_de_week_news_show:
    pattern:  /nieuws/{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:News:show }
    requirements:
        _method:  GET

stef_dag_van_de_week_contact:
    pattern:  /contact
    defaults: { _controller: StefDagVanDeWeekBundle:Index:contact }

stef_dag_van_de_week_today_in_the_past:
    pattern:  /vandaag-in-het-verleden
    defaults: { _controller: StefDagVanDeWeekBundle:TodayInThePast:showTodayInThePast }

stef_dag_van_de_week_today:
    pattern:  /vandaag
    defaults: { _controller: StefDagVanDeWeekBundle:TodayInThePast:showToday }

stef_dag_van_de_week_month:
    pattern:  /maandoverzicht-{dutchMonthName}
    defaults: { _controller: StefDagVanDeWeekBundle:Month:showMonth }
    requirements:
       dutchMonthName: januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december

stef_dag_van_de_week_day_by_day:
    pattern:  /{day}-{dutchMonthName}
    defaults: { _controller: StefDagVanDeWeekBundle:DayByDay:showToday }
    requirements:
       day: \d+
       dutchMonthName: januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december

stef_dag_van_de_week_website_pages:
    pattern:  /{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:Page:show }
    requirements:
        _method:  GET
        slug: .+