stef_dag_van_de_week_homepage:
    path:     /
    defaults: { _controller: StefDagVanDeWeekBundle:Index:index }

stef_dag_van_de_week_news_archive_index:
    pattern:  /nieuws
    defaults: { _controller: StefDagVanDeWeekBundle:News:showMainNewsPage }
    requirements:
        _method:  GET

stef_dag_van_de_week_news_show:
    pattern:  /nieuws/{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:News:show }
    requirements:
        _method:  GET

stef_dag_van_de_week_calendar_show:
    pattern:  /kalender/{year}
    defaults: { _controller: StefDagVanDeWeekBundle:Calendar:show }
    requirements:
        _method:  GET

stef_dag_van_de_week_history_article_show:
    pattern:  /historie/{year}/{month}/{day}/{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showArticle }
    requirements:
        _method:  GET

stef_dag_van_de_week_histoy_year_show:
    pattern:  /historie/{year}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showByYear }
    requirements:
        _method:  GET
