stef_dag_van_de_week_calendar_show:
    path:  /kalender/{year}
    defaults: { _controller: StefDagVanDeWeekBundle:Calendar:show }
    methods: [GET]

stef_dag_van_de_week_calendar_index:
    path:  /kalender
    defaults: { _controller: StefDagVanDeWeekBundle:Calendar:showIndex }
    methods: [GET]