stef_dag_van_de_week_history_article_show:
    path:  /historie/{year}/{month}/{day}/{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showArticle }
    methods: [GET]

stef_dag_van_de_week_history_year_month_day_show:
    path:  /historie/{year}/{month}/{day}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showByYearMonthDay }
    methods: [GET]

stef_dag_van_de_week_history_year_month_show:
    path:  /historie/{year}/{month}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showByYearMonth }
    methods: [GET]

stef_dag_van_de_week_history_year_show:
    path:  /historie/{year}
    defaults: { _controller: StefDagVanDeWeekBundle:History:showByYear }
    methods: [GET]

stef_dag_van_de_week_history_index:
    path:  /historie
    defaults: { _controller: StefDagVanDeWeekBundle:History:showIndex }
    methods: [GET]