stef_dag_van_de_week_homepage:
    path:     /
    defaults: { _controller: StefDagVanDeWeekBundle:Index:index }

stef_dag_van_de_week_sitemaps_monthdays:
    path:  '/sitemaps/{month}-per-day.xml'
    defaults: { _controller: StefDagVanDeWeekBundle:Sitemap:generateByMonthPerDay }
    methods: [GET]
    requirements:
        month: januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december
        _format:  xml

stef_dag_van_de_week_sitemaps_history:
    path:  /sitemaps/{month}.xml
    defaults: { _controller: StefDagVanDeWeekBundle:Sitemap:generateByMonth }
    methods: [GET]
    requirements:
        month: januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december
        _format:  xml

stef_dag_van_de_week_sitemaps:
    path:  /sitemaps/{mappingKey}.xml
    defaults: { _controller: StefDagVanDeWeekBundle:Sitemap:generate }
    methods: [GET]
    requirements:
        _format:  xml

stef_dag_van_de_week_calendar_routing:
    resource: "@StefDagVanDeWeekBundle/Resources/config/calendar_routing.yml"

stef_dag_van_de_week_history_routing:
    resource: "@StefDagVanDeWeekBundle/Resources/config/history_routing.yml"

stef_dag_van_de_week_weekhero_routing:
    resource: "@StefDagVanDeWeekBundle/Resources/config/weekhero_routing.yml"

stef_dag_van_de_week_special_days_by_year:
    path:  /bijzondere-dagen-{year}
    defaults: { _controller: StefDagVanDeWeekBundle:SpecialDates:show }
    methods: [GET]
    requirements:
        year:  \d+

stef_dag_van_de_week_news_archive_index:
    path:  /nieuws
    defaults: { _controller: StefDagVanDeWeekBundle:News:showMainNewsPage }
    methods: [GET]

stef_dag_van_de_week_news_show:
    path:  /nieuws/{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:News:show }
    methods: [GET]

stef_dag_van_de_week_contact:
    path:  /contact
    defaults: { _controller: StefDagVanDeWeekBundle:Index:contact }

stef_dag_van_de_week_today_in_the_past:
    path:  /vandaag-in-het-verleden
    defaults: { _controller: StefDagVanDeWeekBundle:TodayInThePast:showTodayInThePast }

stef_dag_van_de_week_today:
    path:  /vandaag
    defaults: { _controller: StefDagVanDeWeekBundle:TodayInThePast:showToday }

stef_dag_van_de_week_month:
    path:  /maandoverzicht-{dutchMonthName}
    defaults: { _controller: StefDagVanDeWeekBundle:Month:showMonth }
    requirements:
       dutchMonthName: januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december

stef_dag_van_de_week_day_by_day:
    path:  /{day}-{dutchMonthName}
    defaults: { _controller: StefDagVanDeWeekBundle:DayByDay:showToday }
    requirements:
       day: \d+
       dutchMonthName: januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december

stef_dag_van_de_week_website_pages:
    path:  /{slug}
    defaults: { _controller: StefDagVanDeWeekBundle:Page:show }
    methods: [GET]
    requirements:
        slug: .+