services:
    stef.twig.leap_extension:
        class: Stef\DagVanDeWeekBundle\Twig\Extension\IsLeapYearExtension
        tags:
            - { name: twig.extension }

    stef.twig.century_extension:
        class: Stef\DagVanDeWeekBundle\Twig\Extension\IsCenturyYearExtension
        tags:
            - { name: twig.extension }

    stef.twig.weekday_extension:
        class: Stef\DagVanDeWeekBundle\Twig\Extension\GetTranslatedWeekdayExtension
        tags:
            - { name: twig.extension }

    stef.twig.month_extension:
        class: Stef\DagVanDeWeekBundle\Twig\Extension\GetTranslatedMonthExtension
        tags:
            - { name: twig.extension }

    stef_simple_cms.history_year_manager:
        class: Stef\DagVanDeWeekBundle\Manager\HistoryYearManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.contact_manager:
        class: Stef\DagVanDeWeekBundle\Manager\ContactManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.history_manager:
        class: Stef\DagVanDeWeekBundle\Manager\HistoryManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.calendar_year_manager:
        class: Stef\DagVanDeWeekBundle\Manager\CalendarYearManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.weekhero_manager:
        class: Stef\DagVanDeWeekBundle\Manager\WeekHeroManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.day_manager:
        class: Stef\DagVanDeWeekBundle\Manager\DayManager
        arguments: ["@doctrine.orm.entity_manager"]

    stef_simple_cms.entity_mapper:
        class: Stefanius\SimpleCmsBundle\EntityMapper\Mapper
        calls:
            - [addNewMapping, ["News", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.news_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["Page", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.page_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["Dictionary", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.dictionary_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["User", "StefSimpleCmsBundle", "Stefanius\\SimpleCmsBundle\\Entity", "@stef_simple_cms.user_manager", "Stefanius\\SimpleCmsBundle\\Form\\NewsType"]]
            - [addNewMapping, ["CalendarYear", "StefDagVanDeWeekBundle", "Stef\\DagVanDeWeekBundle\\Entity", "@stef_simple_cms.calendar_year_manager"]]
            - [addNewMapping, ["HistoryYear", "StefDagVanDeWeekBundle", "Stef\\DagVanDeWeekBundle\\Entity", "@stef_simple_cms.history_year_manager"]]
            - [addNewMapping, ["History", "StefDagVanDeWeekBundle", "Stef\\DagVanDeWeekBundle\\Entity", "@stef_simple_cms.history_manager"]]
            - [addNewMapping, ["Contact", "StefDagVanDeWeekBundle", "Stef\\DagVanDeWeekBundle\\Entity", "@stef_simple_cms.contact_manager"]]
            - [addNewMapping, ["Day", "StefDagVanDeWeekBundle", "Stef\\DagVanDeWeekBundle\\Entity", "@stef_simple_cms.day_manager"]]
