stef_dag_van_de_week_weekhero_show:
    path:  /topper-van-de-week/{year}/{week}
    defaults: { _controller: StefDagVanDeWeekBundle:WeekHero:show }
    methods: [GET]

stef_dag_van_de_week_weekhero_year_index:
    path:  /topper-van-de-week/{year}
    defaults: { _controller: StefDagVanDeWeekBundle:WeekHero:showByYear }
    methods: [GET]