sudo: false
language: php

php:
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - composer self-update

before_script:
  - composer install --no-interaction --no-scripts

script:
  - ./sites/dagvandeweek/public_html/vendor/bin/phpunit --coverage-clover=coverage.clover
